# SESSION - 2.

# QUESTION - 1.

In [1]:
import numpy as np

In [10]:
a = np.random.randint(1,6,(4,5))
print("the 4 × 5 array is :",a)

print("\n the first index to third index is :",a[1:3])

the 4 × 5 array is : [[5 5 1 5 3]
 [2 3 2 4 4]
 [3 2 3 5 1]
 [3 1 5 3 3]]

 the first index to third index is : [[2 3 2 4 4]
 [3 2 3 5 1]]


# QUESTION - 2.

In [18]:
b = np.array([5000,7000,9000,6000,2000,12000,1000,13000,14000,500])
print('the actual array is ;',b)

c = b[b>8000]
print("the 8000 greather than steps print is :",c)

the actual array is ; [ 5000  7000  9000  6000  2000 12000  1000 13000 14000   500]
the 8000 greather than steps print is : [ 9000 12000 13000 14000]


# QUESTION - 3.

In [19]:
scores = np.array([185, 210, 156, 198, 175, 220, 190, 165])

print("IPL team scores:", scores)

print("Score of Match 2:", scores[1])
print("Score of Match 5:", scores[4])
print("Score of Match 7:", scores[6])


IPL team scores: [185 210 156 198 175 220 190 165]
Score of Match 2: 210
Score of Match 5: 175
Score of Match 7: 190


# QUESTION - 4.

In [25]:
prices = np.random.randint(100,201,(3,3))
print("the original product prices is :",prices)

new_prices = prices - prices *10 / 100
print("after discount the product prices is :",new_prices)

the original product prices is : [[165 160 132]
 [105 109 136]
 [194 190 138]]
after discount the product prices is : [[148.5 144.  118.8]
 [ 94.5  98.1 122.4]
 [174.6 171.  124.2]]


# QUESTION - 5.

In [40]:
ratings = np.random.randn(3,3)
print("the orginal ratings is :",ratings)

ratings[ratings < 0] = 0
print("\n ratings after replacing negative values with 0:",ratings)

the orginal ratings is : [[-0.45984695 -2.34306842  0.65165075]
 [-0.42210779 -2.12464372  1.17089468]
 [ 0.95525224 -0.42363495  1.18504256]]

 ratings after replacing negative values with 0: [[0.         0.         0.65165075]
 [0.         0.         1.17089468]
 [0.95525224 0.         1.18504256]]
