In [2]:
import numpy as np

In [8]:
friend1 = np.array([5000, 7000, 8500, 6000, 9000, 7500, 10000])

friend2 = np.array([6000, 6500, 8000, 7000, 9500, 8000, 9000])

print("the addition of this array is ;",friend1 + friend2)
print("the substraction of this array is :",friend1 - friend2)
print("the multiplication of this array is ;",friend1 * friend2)
print("the devision of this array is ;",friend1 / friend2)


the addition of this array is ; [11000 13500 16500 13000 18500 15500 19000]
the substraction of this array is : [-1000   500   500 -1000  -500  -500  1000]
the multiplication of this array is ; [30000000 45500000 68000000 42000000 85500000 60000000 90000000]
the devision of this array is ; [0.83333333 1.07692308 1.0625     0.85714286 0.94736842 0.9375
 1.11111111]


# QUESTION - 2.

In [11]:
user_preferences = np.array([
    [5, 3, 2],
    [4, 5, 3],
    [2, 4, 5]
])


song_popularity = np.array([
    [4, 2, 3],
    [3, 5, 2],
    [2, 3, 5]
])


result_dot = np.dot(user_preferences, song_popularity)

print("Result using dot():")
print(result_dot)

result_matmul = np.matmul(user_preferences, song_popularity)

print("Result using matmul():")
print(result_matmul)

# Difference:
# For 2D matrices, np.dot() and np.matmul() give the same result.
# np.dot() is a general dot product function,
# while np.matmul() is specifically used for matrix multiplication.

# Main point:** 3 * 3 matrices ke case mein `dot()` aur `matmul()` ka result same hai. 


Result using dot():
[[33 31 31]
 [37 42 37]
 [30 39 39]]
Result using matmul():
[[33 31 31]
 [37 42 37]
 [30 39 39]]


# QUESTION - 3.

In [12]:
pixels = np.array([
    [120, 150, 200, 180],
    [90,  110, 160, 140],
    [200, 220, 180, 170],
    [130, 100, 190, 210]
])

print("Original pixel matrix:")
print(pixels)

transposed = pixels.T

print("\nTransposed matrix:")
print(transposed)

print("\nMean:", np.mean(pixels))
print("Median:", np.median(pixels))
print("Standard Deviation:", np.std(pixels))
print("Variance:", np.var(pixels))



Original pixel matrix:
[[120 150 200 180]
 [ 90 110 160 140]
 [200 220 180 170]
 [130 100 190 210]]

Transposed matrix:
[[120  90 200 130]
 [150 110 220 100]
 [200 160 180 190]
 [180 140 170 210]]

Mean: 159.375
Median: 165.0
Standard Deviation: 39.60251728110222
Variance: 1568.359375


# QUESTION - 4.

In [28]:
matrix = np.random.randint(1,6,(3,3))
print("the 3 cross 3 matrix is :")
print(matrix)

determinant = np.linalg.det(matrix)
print("\n the determinant of this matrix is ;",determinant)

inverse = np.linalg.inv(matrix)
print("\n the inverse of this matrix is ;")
print(inverse)

eigvalues = np.linalg.eig(matrix)
print("\n the eigen vectors and eigen values is :")
print(eigvalues)

the 3 cross 3 matrix is :
[[5 1 1]
 [1 4 5]
 [2 5 3]]

 the determinant of this matrix is ; -61.00000000000001

 the inverse of this matrix is ;
[[ 0.21311475 -0.03278689 -0.01639344]
 [-0.1147541  -0.21311475  0.39344262]
 [ 0.04918033  0.37704918 -0.31147541]]

 the eigen vectors and eigen values is :
EigResult(eigenvalues=array([ 9.22271563,  4.31138594, -1.53410157]), eigenvectors=array([[ 0.31748376,  0.88951293, -0.01128607],
       [ 0.68677465, -0.40914794, -0.66922752],
       [ 0.65386898, -0.20338317,  0.74297183]]))


# QUESTION - 5.

In [44]:
array = np.array([[11,12,33,44,77,88],[1,2,3,4,5,6]])
print("the array is :")
print(array)

array2 = np.reshape(array,(3,4))
print("\nthe reshape array is :")
print(array2)

array3 = array2.flatten()
print("\nthe flatten array is :")
print(array3)

part1, part2 = np.split(array3, 2)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

stacked = np.vstack((part1, part2))

print("\nVertically stacked array:")
print(stacked)

the array is :
[[11 12 33 44 77 88]
 [ 1  2  3  4  5  6]]

the reshape array is :
[[11 12 33 44]
 [77 88  1  2]
 [ 3  4  5  6]]

the flatten array is :
[11 12 33 44 77 88  1  2  3  4  5  6]

Part 1:
[11 12 33 44 77 88]

Part 2:
[1 2 3 4 5 6]

Vertically stacked array:
[[11 12 33 44 77 88]
 [ 1  2  3  4  5  6]]
